version: '3.4'

x-environment:
    &common-environment-variables
    DEBUG: 'true'
    REDIS_DEFAULT_DSN: redis://redis:6379/0
    PSQL_DSN: postgresql+psycopg2://gocomet_read_write:goCometCrawler123@postgresql/gocomet_crawler

services:
    postgresql:
        image: postgres:10.11
        container_name: postgresql
        hostname: postgresql
        environment:
            - POSTGRES_DB=gocomet_crawler
            - POSTGRES_USER=gocomet_read_write
            - POSTGRES_PASSWORD=goCometCrawler123
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    redis:
        image: redis:5.0.5-alpine
        container_name: redis
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data

    crawler-medium:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - "postgresql"
            - "redis"
        hostname: crawler-medium
        container_name: crawler-medium
        ports:
            - "8000:80"
        image: crawler-medium:latest
        volumes:
            - .:/srv/crawler-medium
        stdin_open: true
        tty: true
        environment:
            <<: *common-environment-variables
