"""Updated date format

Revision ID: 409ae9e7928c
Revises: 8a4dde785adb
Create Date: 2021-07-01 21:26:08.243141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409ae9e7928c'
down_revision = '8a4dde785adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
