"""Added tables

Revision ID: 8a4dde785adb
Revises: 
Create Date: 2021-07-01 20:23:20.442276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a4dde785adb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'author_name', name='_author_uc')
    )
    op.create_index('idx_author', 'author', ['author_id'], unique=False)
    op.create_index('ix_author_created_on', 'author', ['created_time'], unique=False)
    op.create_index(op.f('ix_author_created_time'), 'author', ['created_time'], unique=False)
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_index('ix_tag_name', 'tags', ['tag_name'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('blog_desc', sa.String(length=3000), nullable=True),
    sa.Column('blog_data', sa.String(), nullable=True),
    sa.Column('blog_link', sa.String(length=512), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('read_time', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Integer(), as_tuple=sa.ForeignKey('tags.id')), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'title', 'blog_desc', 'blog_data', 'blog_link', 'author_id', 'read_time', 'tags', name='_blogs_uc')
    )
    op.create_index('idx_primary_identifier', 'blogs', ['post_id'], unique=False)
    op.create_index(op.f('ix_blogs_author_id'), 'blogs', ['author_id'], unique=False)
    op.create_index(op.f('ix_blogs_created_time'), 'blogs', ['created_time'], unique=False)
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    op.create_index('ix_combined_created_id', 'blogs', ['post_id', 'created_time'], unique=False)
    op.create_index('ix_created_on', 'blogs', ['created_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_created_on', table_name='blogs')
    op.drop_index('ix_combined_created_id', table_name='blogs')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_created_time'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_author_id'), table_name='blogs')
    op.drop_index('idx_primary_identifier', table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('ix_tag_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_index(op.f('ix_author_created_time'), table_name='author')
    op.drop_index('ix_author_created_on', table_name='author')
    op.drop_index('idx_primary_identifier', table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
