"""Updated index

Revision ID: 9f962577cb35
Revises: 8a4dde785adb
Create Date: 2021-07-02 08:56:03.079154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f962577cb35'
down_revision = '8a4dde785adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_blogs_uc', 'blogs', type_='unique')
    op.create_unique_constraint('_blogs_uc', 'blogs', ['post_id', 'title', 'blog_desc', 'blog_link', 'author_id', 'read_time', 'tags'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_blogs_uc', 'blogs', type_='unique')
    op.create_unique_constraint('_blogs_uc', 'blogs', ['post_id', 'title', 'blog_desc', 'blog_data', 'blog_link', 'author_id', 'read_time', 'tags'])
    # ### end Alembic commands ###
